version: '3.1'
services:
        web:
                image: odoo:14.0
                depends_on:
                        - db
                ports:
                        - "8069:8069"
                environment:
                        - HOST=db
                        - USER=odoo
                        - PASSWORD=myodoo
                volumes:
                        - odoo-data:/var/lib/odoo
        db:
                image: postgres:latest
                environment:
                        - POSTGRES_DB=postgres
                        - POSTGRES_PASSWORD=myodoo
                        - POSTGRES_USER=odoo
                        - PGDATA=/var/lib/postgresql/data/pgdata
                volumes:
                        - odoo-db:/var/lib/postgresql/data/pgdata
volumes:
        odoo-data:
        odoo-db:
